### ISSUE TITLE
Als werkgever wil ik in een vacature kunnen aangeven wat het contracttype, contractduur, werkuren, salaris, locatie, vereisten en beschrijving zijn, zodat werknemers precies weten waar ze aan toe zijn.

### ISSUE THREAD

**Issue by Mathijs-04** [Mathijs-04/TLE1-Agency#5]
**Acceptatiecriteria**
- [x] Als werkgever wil ik tijdens het aanmaken van een vacature verschillende invulvelden hebben voor vacatureeisen

**Defenition Of Done**
- [x] WCAG A-level
- [x] Geen bugs of errors
- [x] Engelse code, Nederlandse comments
- [x] Desktop interface
- [x] Voldoet aan de Style Guide
- [x] Volledige beveiliging volgens OWASP

**Comment by ItsMySquid** [comment]
Nederlandse comments en wcag in het engels bij image uploaden
