### ISSUE TITLE
Als werkgever wil ik een bepaald aantal mensen kunnen uitnodigen en hierbij een startdatum kunnen aangeven zodat ik me kan voorbereiden om de nieuwe werknemers te ontvangen.

### ISSUE THREAD

**Issue by Mathijs-04** [Mathijs-04/TLE1-Agency#6]
**Acceptatiecriteria**
- [x] De werkgever kan een startdatum selecteren voor de uitnodiging.
- [x] Er is een functie beschikbaar om meerdere mensen te selecteren en uit te nodigen via een formulier.
- [x] Er is een bevestigingsmail

**Defenition Of Done**
- [x] WCAG A-level
- [x] Geen bugs of errors
- [x] Engelse code, Nederlandse comments
- [x] Desktop interface
- [x] Voldoet aan de Style Guide
- [x] Volledige beveiliging volgens OWASP

**Comment by jaimyvdb03** [comment]
Comments in de code toevoegen!!!
